<a href="https://colab.research.google.com/github/Eddie-Anna/Ant-Feeding-Simulation-NetLogo/blob/SKILL-SET/SAFINATU_PYTHON.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**INTRODUCTION**

Welcome to Python for Data Analysis

I like this class

In [292]:
print(3+7)
print(5*2)

10
10

In [293]:
# This is a
3+7

10

In [294]:
print(7)

7

# Fundmentals of Python 3

In [295]:
print(20)

20

In [296]:
print(3+6)

9

In [297]:
print(0.85)

0.85

In [298]:
print(1e6)
print(1E9)

1000000.0
1000000000.0

In [299]:
print(1e-3)
print(1e-5)
print(1E-9)

0.001
1e-05
1e-09

In [300]:
print("HELLO WORLD")
print("LADY")

HELLO WORLD
LADY

In [301]:
print("PRAISE")

PRAISE

# Python as a Calculator

Addition

In [302]:
print(3+7)

10

In [303]:
print(3 + 7)

10

Subtraction

In [304]:
print(7-3)

4

In [305]:
print(3-7)

-4

Multiplication

In [306]:
print(3*8)

24

Division

In [307]:
print(5/2)

2.5

In [308]:
print(75/5)

15.0

Integer Division

In [309]:
print(5//2)

2

In [310]:
print(8//3)

2

In [311]:
print(100//3)

33

Power Function

In [312]:
print(5**3)

125

In [313]:
pow(5,3)

125

In [314]:
9**0.5

3.0

Modulus Function/Symbol

In [315]:
print(5%3)

2

In [316]:
print(68%7)

5

In [317]:
print(4%2)

0

In [318]:
print((1+2)*3)

9

In [319]:
print(1+(2*3))

7

In [320]:
0.5*100

50.0

Type Function

In [321]:
type("Sun")

str

In [322]:
type(187)

int

In [323]:
type(2.5)

float

In [324]:
type(True)

bool

In [325]:
print("4a")
print(3)
print(3.0)

4a
3
3.0

Variables

In [326]:
age = 3*5

In [327]:
print(age)

15

In [328]:
print(3 * age)

45

In [329]:
fruit = "APPLE"
print(fruit)

APPLE

In [330]:
age = 21
print (age)

21

## Data Structures in Python 3

List

In [331]:
[1,2,3,4,5]

[1, 2, 3, 4, 5]

In [332]:
type([1,2,3,4,5])

list

In [333]:
mixed = ["fruits",12,2,5,False]

In [334]:
print(mixed)
type(mixed)

['fruits', 12, 2, 5, False]

list

Python Methods (strings and lists)

In [335]:
mixed.append(30)

In [336]:
print(mixed)

['fruits', 12, 2, 5, False, 30]

In [337]:
mixed.remove(30)

In [338]:
print(mixed)

['fruits', 12, 2, 5, False]

In [339]:
name = "EDORA"
print("my name is "+ name)
print(f"my name is {name}")

my name is EDORA
my name is EDORA

In [340]:
"Hello" + " " + "World"

'Hello World'

In [341]:
odd_numbers = [1,3,5,7,9,11,13]
even_numbers = [2,4,6,8,10,12,14]

In [342]:
print(odd_numbers)

[1, 3, 5, 7, 9, 11, 13]

Positive Indexing

In [343]:
print(odd_numbers[0])
print(odd_numbers[1])
print(odd_numbers[2])
print(odd_numbers[5])

odd_numbers_new = odd_numbers + [15,17]
print(odd_numbers_new)

1
3
5
11
[1, 3, 5, 7, 9, 11, 13, 15, 17]

Negative Indexing

In [344]:
print(odd_numbers[-2])
print(odd_numbers[-1])

11
13

In [345]:
print(odd_numbers[2:4])

[5, 7]

In [346]:
type((1,2,3,4))

tuple

Set/Dictionary

In [347]:
numbers = {1,2,3,4,5}
print(type(numbers))

<class 'set'>

In [348]:
contact = {
    "name" : "EDORA",
    "class" : "Data Analysis",
    "age" : 21
}

In [349]:
print(contact)
type(contact)

{'name': 'EDORA', 'class': 'Data Analysis', 'age': 21}

dict

In [350]:
contact = {
    "name" : "EDORA",
    "class" : "Data Analysis",
    "age" : 21
}

In [351]:
contact.keys()

dict_keys(['name', 'class', 'age'])

In [352]:
contact.values()

dict_values(['EDORA', 'Data Analysis', 21])

### Looping in Python 3

In [353]:
person = ["victoria", 25,"trader", "korea",[1999,"September",9]]

In [354]:
for i in person:
  print(i)

victoria
25
trader
korea
[1999, 'September', 9]

In [355]:
for a in even_numbers:
  print(f"{a} is multlied by 2 to give {a*2}")

2 is multlied by 2 to give 4
4 is multlied by 2 to give 8
6 is multlied by 2 to give 12
8 is multlied by 2 to give 16
10 is multlied by 2 to give 20
12 is multlied by 2 to give 24
14 is multlied by 2 to give 28

In [356]:
nigerian_players =["Osimhen","Iwobi","A. Adams","Onyeka","Lookman","Nwabill","Bassey","Aina","Bruno"]

In [357]:
for i in nigerian_players:
  print(i)

Osimhen
Iwobi
A. Adams
Onyeka
Lookman
Nwabill
Bassey
Aina
Bruno

In [358]:
korean_movies = ["Moonshine", "Business Proposal", "Alchemy of Souls", "Fiery Priest", "Jewel in Palace", "Musicians"]

In [359]:
for k in korean_movies:
  print(k)

Moonshine
Business Proposal
Alchemy of Souls
Fiery Priest
Jewel in Palace
Musicians

While Loop Statement

In [360]:
countdown = 10

In [361]:
while countdown > 0:
  print(f"{countdown} seconds left")
  countdown-=1

10 seconds left
9 seconds left
8 seconds left
7 seconds left
6 seconds left
5 seconds left
4 seconds left
3 seconds left
2 seconds left
1 seconds left

Conditional Statements

- if
- elif
- else

In [362]:

Age = 16

In [363]:
if Age >=18:
  print("This is an Adult")
elif Age >=13:
  print("This is a Teenager")
else:
  print("This is a Child")

This is a Teenager

In [364]:
score = 56

In [365]:
if score >=70:
  print("A")
elif score >=60:
  print("B")
elif score >=50:
    print("C")
elif score >=45:
  print("D")
else:
  print("f")

C

# Python Libraris for Data Analysis

# Numpy - Numerical Python

In [366]:
import numpy as np

In [367]:
prime = [1,2,8,7]
type(prime)

list

In [368]:
prime1 = np.array(prime)
print(prime1)
type(prime1)

[1 2 8 7]

numpy.ndarray

In [369]:
prime1.shape

(4,)

In [370]:
np.mean(prime)

np.float64(4.5)

In [371]:
np.median(prime)

np.float64(4.5)

In [372]:
arr1 = [[1,2,3],[4,5,6]]
print(arr1)

[[1, 2, 3], [4, 5, 6]]

In [373]:
arr1 = np.array(arr)
print(arr1)

[[1 2 3]
 [4 5 6]]

In [374]:
arr1.shape

(2, 3)

In [375]:
np.random.random((2,3))

array([[0.31349309, 0.35779594, 0.83624595],
       [0.60846275, 0.61253631, 0.22986774]])

Pandas

In [376]:
import pandas as pd

In [377]:

days = pd.Series(["Monday","Tuesday","Wednesday"], index = ["a","b","c"])
print(days)

a       Monday
b      Tuesday
c    Wednesday
dtype: object

In [378]:
df_dict = {
    "country":["Nigeria","Ghana","Mali","Togo","Algeria"],
    "capital":["Abuja","Accra","Bamako","Lome","Algiers"],
    "population":[300000,150000,100000,30000,50000],
    "AV_age":[23,28,30,35,37]
}

In [379]:
print(df_dict)

{'country': ['Nigeria', 'Ghana', 'Mali', 'Togo', 'Algeria'], 'capital': ['Abuja', 'Accra', 'Bamako', 'Lome', 'Algiers'], 'population': [300000, 150000, 100000, 30000, 50000], 'AV_age': [23, 28, 30, 35, 37]}

In [388]:
df = pd.DataFrame(df_dict,index=["a","b","c","d","e"])
print(df)

   country  capital  population  AV_age
a  Nigeria    Abuja      300000      23
b    Ghana    Accra      150000      28
c     Mali   Bamako      100000      30
d     Togo     Lome       30000      35
e  Algeria  Algiers       50000      37

In [389]:
df.reset_index()

  index  country  capital  population  AV_age
0     a  Nigeria    Abuja      300000      23
1     b    Ghana    Accra      150000      28
2     c     Mali   Bamako      100000      30
3     d     Togo     Lome       30000      35
4     e  Algeria  Algiers       50000      37

In [390]:
df.iloc[2]

country         Mali
capital       Bamako
population    100000
AV_age            30
Name: c, dtype: object

In [392]:
df.loc['a']

country       Nigeria
capital         Abuja
population     300000
AV_age             23
Name: a, dtype: object

In [393]:
df["capital"]

a      Abuja
b      Accra
c     Bamako
d       Lome
e    Algiers
Name: capital, dtype: object

In [394]:
df.columns

Index(['country', 'capital', 'population', 'AV_age'], dtype='object')

In [395]:
df.shape

(5, 4)

In [397]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     5 non-null      object
 1   capital     5 non-null      object
 2   population  5 non-null      int64
 3   AV_age      5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 372.0+ bytes

In [398]:
df.describe()

          population    AV_age
count       5.000000   5.00000
mean   126000.000000  30.60000
std    107842.477716   5.59464
min     30000.000000  23.00000
25%     50000.000000  28.00000
50%    100000.000000  30.00000
75%    150000.000000  35.00000
max    300000.000000  37.00000